[package]
name = "stockholm"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
chrono = "0.4.43"
clap = { version = "4.5.56", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"
sha2 = "0.10.9"
tracing-subscriber = "0.3.22"
